### PR TITLE
Add dialog component

### PR DESCRIPTION
**Pull request by izzudin26**
write code for display dialog quote card

### CODE REVIEW

**Comment by nyancodeid** [comment]
Wow, that's awesome. But can we animate the quote-card only rather than we animate the overlay background. So the scale animation should apply to quote-card only and overlay background should immediately open.

**Comment by izzudin26** [comment]
its mean we just remove overlay background and scale up quote-card without overlay background ?

**Comment by nyancodeid** [comment]
No, the overlay and blur effects are awesome. And this is what I mean

https://user-images.githubusercontent.com/24630806/135791334-a9f37334-3a18-4900-8b72-b4809a4d630b.mp4

**Comment by nyancodeid** [comment]
> No, the overlay and blur effects are awesome. And this is what I mean
> 
>  vokoscreenNG-2021-10-04_11-08-07.mp4

If you don't mind we can use animation like above.

**Pull request merged**
