### PR TITLE
Quotes by Habib Husein Ja'far

### PR DESCRIPTION
**Pull request by ayatullahnaufal**
Kata-kata motivasi dari Habib Husein Ja'far

### CODE REVIEW

**Comment by nyancodeid** [comment]
Awesome, but can you fix the last quote `created_at` date. It should be a date not an athor. Thank you @ayatullahnaufal

**Comment by nyancodeid** [comment]
Nevermind, I will help you fix them. Thanks @ayatullahnaufal

**Comment by ayatullahnaufal** [comment]
ohh sory, thank u for help 🙏 @nyancodeid

**Comment by nyancodeid** [comment]
No problem

**Pull request merged**
