### PR TITLE
Feat quotes/habibiaboy

### PR DESCRIPTION
**Pull request by habibiaboy**

### CODE REVIEW

**Comment by nyancodeid** [comment]
Awesome, can we exclude `package-lock.json` here?

**Comment by habibiaboy** [comment]
it does not matter

**Comment by nyancodeid** [comment]
For our deployment, yes its matter. Please commit only `.yaml` file only.

**Comment by habibiaboy** [comment]
donee , I have re-pushed

**Comment by nyancodeid** [comment]
Unfortunately, I still see the file `package-lock.json` on files changes. If necessary, you can make another PR by only committing the .yaml file

**Comment by habibiaboy** [comment]
done bruh, with new branch, i have repushed

**Comment by nyancodeid** [comment]
It's still see package-lock.json on files changed. I am gonna close this PR. So you can create a new one, but only edit `.yaml` file. Thank you @habibiaboy

**Pull request closed without merging**
