### PR TITLE
Added quote to /quotes

### PR DESCRIPTION
**Pull request by ankur12-1610**
Added quote to `/quotes` directory.

### CODE REVIEW

**Comment by ankur12-1610** [comment]
Please review the PR!

**Comment by nyancodeid** [comment]
It's really 5 October 2021 in your place now?

**Comment by ankur12-1610** [comment]
> It's really 5 October 2021 in your place now? In what country do you live

Sorry I entered the wrong date.

I have committed the changes, please review them.

**Comment by nyancodeid** [comment]
Awesome, thank you @ankur12-1610

**Pull request merged**
